flowchart LR
  subgraph React["React / src"]
    App["src/App.tsx"]
    component["src/component"]
    parts["src/parts"]
    action["src/action"]
    service["src/service"]
    repository["src/repository"]
    store["src/store"]
    model["src/model"]
  end

  subgraph Shared["Shared"]
    core["core"]
  end

  subgraph Electron["Electron"]
    eservice["electron/service"]
    eentity["electron/entity"]
    erepository["electron/repository"]
    eipc["electron/ipc"]
  end

  App --> component

  component --> action
  component --> parts
  component --> model

  action --> service
  action --> store
  action --> model

  service --> repository
  service --> model

  repository --> model
  repository --> core

  store --> model

  model

  core --> core

  eservice --> eentity
  eservice --> erepository

  erepository --> eentity

  eipc --> eservice
  eipc --> core

  eentity

